// Generated by scripts/render_runtime_config.sh. Do not edit by hand.
window.MARKET_BOT_RUNTIME_MODE = "local";
window.MARKET_BOT_LOCAL_API_BASE = "http://127.0.0.1:8000";
window.MARKET_BOT_API_BASE = "";
