#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT_DIR/.env}"
TARGET="$ROOT_DIR/apps/web/prototype/config.js"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

MODE="${MARKET_BOT_RUNTIME_MODE:-local}"
LOCAL_HOST="${MARKET_BOT_LOCAL_BACKEND_HOST:-127.0.0.1}"
LOCAL_PORT="${MARKET_BOT_LOCAL_BACKEND_PORT:-8000}"
LOCAL_API_BASE="http://${LOCAL_HOST}:${LOCAL_PORT}"
HOSTED_API_BASE="${MARKET_BOT_HOSTED_API_BASE:-}"

case "$MODE" in
  local)
    API_BASE=""
    ;;
  host)
    API_BASE="${HOSTED_API_BASE%/}"
    ;;
  *)
    echo "[runtime-config] invalid MARKET_BOT_RUNTIME_MODE=$MODE (expected: local | host)" >&2
    exit 1
    ;;
esac

cat > "$TARGET" <<EOF
// Generated by scripts/render_runtime_config.sh. Do not edit by hand.
window.MARKET_BOT_RUNTIME_MODE = "${MODE}";
window.MARKET_BOT_LOCAL_API_BASE = "${LOCAL_API_BASE}";
window.MARKET_BOT_API_BASE = "${API_BASE}";
EOF

echo "[runtime-config] wrote $TARGET"
echo "[runtime-config] mode=$MODE local_api=$LOCAL_API_BASE api_base=${API_BASE:-"(same-origin fallback)"}"
